// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PeopleServiceClient is the client API for PeopleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeopleServiceClient interface {
	CreateCollegeInfo(ctx context.Context, in *CreateCollegeInfoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetCollegeInfo(ctx context.Context, in *GetCollegeInfoRequest, opts ...grpc.CallOption) (*GetCollegeInfoReply, error)
}

type peopleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeopleServiceClient(cc grpc.ClientConnInterface) PeopleServiceClient {
	return &peopleServiceClient{cc}
}

func (c *peopleServiceClient) CreateCollegeInfo(ctx context.Context, in *CreateCollegeInfoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.classmate.v1.PeopleService/CreateCollegeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peopleServiceClient) GetCollegeInfo(ctx context.Context, in *GetCollegeInfoRequest, opts ...grpc.CallOption) (*GetCollegeInfoReply, error) {
	out := new(GetCollegeInfoReply)
	err := c.cc.Invoke(ctx, "/api.classmate.v1.PeopleService/GetCollegeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeopleServiceServer is the server API for PeopleService service.
// All implementations must embed UnimplementedPeopleServiceServer
// for forward compatibility
type PeopleServiceServer interface {
	CreateCollegeInfo(context.Context, *CreateCollegeInfoRequest) (*empty.Empty, error)
	GetCollegeInfo(context.Context, *GetCollegeInfoRequest) (*GetCollegeInfoReply, error)
	mustEmbedUnimplementedPeopleServiceServer()
}

// UnimplementedPeopleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPeopleServiceServer struct {
}

func (UnimplementedPeopleServiceServer) CreateCollegeInfo(context.Context, *CreateCollegeInfoRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollegeInfo not implemented")
}
func (UnimplementedPeopleServiceServer) GetCollegeInfo(context.Context, *GetCollegeInfoRequest) (*GetCollegeInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollegeInfo not implemented")
}
func (UnimplementedPeopleServiceServer) mustEmbedUnimplementedPeopleServiceServer() {}

// UnsafePeopleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeopleServiceServer will
// result in compilation errors.
type UnsafePeopleServiceServer interface {
	mustEmbedUnimplementedPeopleServiceServer()
}

func RegisterPeopleServiceServer(s grpc.ServiceRegistrar, srv PeopleServiceServer) {
	s.RegisterService(&PeopleService_ServiceDesc, srv)
}

func _PeopleService_CreateCollegeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollegeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeopleServiceServer).CreateCollegeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.classmate.v1.PeopleService/CreateCollegeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeopleServiceServer).CreateCollegeInfo(ctx, req.(*CreateCollegeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeopleService_GetCollegeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollegeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeopleServiceServer).GetCollegeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.classmate.v1.PeopleService/GetCollegeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeopleServiceServer).GetCollegeInfo(ctx, req.(*GetCollegeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeopleService_ServiceDesc is the grpc.ServiceDesc for PeopleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeopleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.classmate.v1.PeopleService",
	HandlerType: (*PeopleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollegeInfo",
			Handler:    _PeopleService_CreateCollegeInfo_Handler,
		},
		{
			MethodName: "GetCollegeInfo",
			Handler:    _PeopleService_GetCollegeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/classmate/v1/classmate.proto",
}
