// Code generated by entc, DO NOT EDIT.

package people

const (
	// Label holds the string label denoting the people type in the database.
	Label = "people"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdnum holds the string denoting the idnum field in the database.
	FieldIdnum = "idnum"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTelephone holds the string denoting the telephone field in the database.
	FieldTelephone = "telephone"
	// Table holds the table name of the people in the database.
	Table = "peoples"
)

// Columns holds all SQL columns for people fields.
var Columns = []string{
	FieldID,
	FieldIdnum,
	FieldName,
	FieldTelephone,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
